### ISSUE TITLE
[BUG] ImportError on import buf/validate

### ISSUE THREAD

**Issue by o-murphy** [bufbuild/protovalidate-python#96]
## Description
if we generate the python sources with buf and --include-imports flag, the protovalidate tries to import buf locally, but if we want to make generated sources a part of other module, the protovalidate raises ImportError on buf/validate import, so we need modify the protovalidate module sources to set where we want to import buf/validate

**Comment by rodaine** [comment]
Hey @o-murphy! Thanks for the report. Can you give more details about the steps you're running and the errors you are seeing?

**Comment by convoi** [comment]
I believe I have the same problem.
My source code is structured like

```
src/my_module/stuff.py
protos/events/v1/some.proto
```


my buf.gen.yaml:
```
# buf.gen.yaml
version: v1

plugins:
  - plugin: buf.build/protocolbuffers/python:v21.9
    out: ./src/my_module
  - plugin: buf.build/protocolbuffers/pyi:v21.9
    out: ./src/my_module
```

I generate my python proto files into my module:

`buf generate --include-imports protos`

This puts the generated python classes and the buf validate files in 
```
src/my_module/events
src/my_module/buf/validate
```
so if I wanted to importe the validate_pb2.py I need to do
```
 from my_module.buf.validate import expression_pb2
```

but protovalidate wants  `from buf.validate import expression_pb2`.

(Disclaimer, to make generated python proto classes work with this module src layout you have to do a sed rewrite trick - I was just hoping that I do not need some other hacks for validation. Also here it would be trickier since I would have to rewrite protovalidate module )
